---
- name: Nginx | install nginx
  apt: pkg=nginx state=installed
  sudo: true

- name: Nginx | nginx settings
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            backup=yes
  sudo: true
  notify:
    - restart nginx

- name: Nginx | disable default server block
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  sudo: true
  notify:
    - restart nginx

- name: Nginx | set default login directory
  lineinfile: dest={{ home_dir }}/.bashrc state=present line='cd {{ sites_dir }}'

- name: Nginx | restart nginx
  service: name=nginx state=restarted
  sudo: true